name: Documentation
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(url="https://github.com/CodeLenz/BMesh.git"); Pkg.add(url="https://github.com/CodeLenz/LMesh.git"); include("docs/make.jl")'
